config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  
  get 'homes/top'
  get 'home/about' => 'homes#about'

  root to: 'homes#top'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :books, only: [:create, :index, :show, :edit, :destroy, :update]

  resources :users, only: [:index, :show, :edit, :update, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord

validates :title, presence: true
validates :body, presence: true, length: { maximum: 200 }

belongs_to :user

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books, dependent: :destroy
  attachment :profile_image

  validates :introduction, length: { maximum: 50 }
  validates :name, presence: true, length: { minimum: 2, maximum: 20 }

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base



before_action :configure_permitted_parameters,if: :devise_controller?

  def after_sign_in_path_for(resource)
    user_path(current_user.id) # ログイン後に遷移するpathを設定
  end


def after_sign_out_path_for(resource)
    homes_top_path # ログアウト後に遷移するpathを設定
end



private

def configure_permitted_parameters
  devise_parameter_sanitizer.permit(:sign_up,keys:[:email])
end


end

app/controllers/books_controller.rb
class BooksController < ApplicationController

before_action :authenticate_user!
before_action :correct_user, only: [:edit, :update]



def index
	@book = Book.new
	@books = Book.all
	@user = User.find(current_user.id)
end

def create
	@book = Book.new(book_params)
	@book.user_id = current_user.id
	@user = User.find(current_user.id)
	@books = Book.all
	if @book.save
		redirect_to book_path(@book.id)
		flash[:notice] = "You have created book successfully."
	else
		render 'index'
	end
end

def show
	@book = Book.new
	@bookers = Book.find(params[:id])
	@user = User.find(@bookers.user.id)
end

def edit
	@book = Book.find(params[:id])
end

def update
	@book = Book.find(params[:id])
	if @book.update(book_params)
		redirect_to book_path(@book.id)
		flash[:notice] = "You have updated book successfully."
	else
		render 'edit'
	end
end

def destroy
	@book = Book.find(params[:id])
	@book.destroy
	redirect_to books_path
end

private

def book_params
	params.require(:book).permit(:title, :body)
end

def correct_user
    @book = Book.find(params[:id])
    redirect_to(books_path)  unless @book.user_id == current_user.id
    end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end

  def about
  end
end

app/controllers/sessions_controller.rb
class SessionsController < Devise::SessionsController

	def destroy
    super
    session[:user_id] = nil
    flash[:notice] = "Signed out successfully."
  	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

before_action :authenticate_user!
before_action :correct_user, only: [:edit, :update]

def index
	@book = Book.new
	@user = User.find(current_user.id)
	@users = User.all
end

def create
	@book = Book.new(book_params)
	@book.user_id = current_user.id
	@user = User.find(current_user.id)
	@books = Book.all
	if @book.save
		redirect_to book_path(@book.id)
		flash[:notice] = "You have created book successfully."
	else
		redirect_to books_path
	end
end


def show
	@book = Book.new
	@user = User.find(params[:id])
	@books = @user.books.all
end

def edit
	@user = User.find(params[:id])
end

def update
	@user = User.find(params[:id])
	if @user.update(user_params)
		redirect_to user_path(@user.id)
		flash[:notice] = "You have updated user successfully."
	else
		render 'edit'
	end
end

def destroy
end

private
def user_params
	params.require(:user).permit(:name, :introduction, :profile_image)
end

def book_params
	params.require(:book).permit(:title, :body)
end

 def correct_user
    @user = User.find(params[:id])
    redirect_to(user_url(current_user)) unless @user == current_user
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/edit.html.erb
<div class="container">
	<div class="row">
<div class="col-md-6 col-md-offset-3">
<h1>Editing Book</h1>
	<%= form_for(@book) do |f| %>
	<% if @book.errors.any? %>
      <h2><%= @book.errors.count %>件のerror</h2>
      <ul>
      <% @book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
  	<% end %>

  	
  	<div class="form-group">
	<label class="form-label">Title</label>
	<%= f.text_field :title, class: "col-xs-12" %>
	</div>
	<div class="form-group">
	<label class="form-label">Opinion</label>
	<%= f.text_area :body, class: "col-xs-12" %>
	</div>
	<%= f.submit 'Update Book', class: "btn btn-primary col-xs-12 updatebutton" %>
	<% end %>

	<div class="link">
	<%= link_to 'Show', book_path(@book.id) %>
	<span>|</span>
	<%= link_to 'Back', books_path %>
 	</div>
</div>
</div>

app/views/books/index.html.erb
<div class="container">
	<div class="row">

<% if flash[:notice] %>
      <div class="flash">
        <%= flash[:notice] %>
      </div>
    <% end %>

<% if @book.errors.any? %>
      <h2><%= @book.errors.count %>件のerror</h2>
      <ul>
      <% @book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
  <% end %>

<div class="col-xs-3">
<div class="user-info-box">
	<h2>User info</h2>
	<div class="image">
		 <%= attachment_image_tag @user, :profile_image, :fill, 100, 100, format: 'jpeg', class: "img-rounded pull-left profile-img", fallback: "no_image.jpg" %> 
	</div>
	<table class="table">
		<tr>
		<th>name</th>
		<th><%= @user.name %></th>
		</tr>
		<tr>
		<th>introduction</th>
		<th><%= @user.introduction %></th>
	 	</tr>
	</table>
	<div class="user-info-configuration">
		<% if @user.id == current_user.id %>
		<%= link_to edit_user_path(@user.id) do %>
			<span class="glyphicon glyphicon-wrench col-xs-12 btn btn-default editbutton" aria-hidden="true"></span>
		<% end %>
		<% end %>
		</div>
</div>

<div class="new-book-box">
	<h2>New book</h2>
	<%= form_for(@book) do |f| %>

	<div class="form-group">
	<label for="book-title">Title</label>
	<%= f.text_field :title, {class: "col-xs-12"} %>
	</div>
	<div class="form-group">
	<label class="book-opinion">Opinion</label>
	<%= f.text_area :body, {class: "col-xs-12"} %>
	</div>
	<div class="form-group">
	<%= f.submit 'Create Book', {class: "btn btn-primary col-xs-12 createbutton"} %>
	</div>
<% end %>
</div>
</div>

<div class="col-xs-9">
<div class="Books-index-box">
	<h2>Books</h2>
	<table class="table">
		<thead>
		<tr>
			<th></th><th>Title</th> <th>opinion</th> 
		</tr>
	    </thead>

	    <tbody>
	    <% @books.each do |book| %>
		<tr>
			<td><%= link_to user_path(book.id) do %>
				<span><%= attachment_image_tag book.user, :profile_image, :fill, 40, 40, format: 'jpeg', class: "img-rounded pull-left profile-img", fallback: "no_image.jpg",size:'40x40' %></span>
				<% end %>
			</td>
			<td><%= link_to book.title, book_path(book.id) %></td>
			<td><%= book.body %></td>
		</tr>
		</tbody>
		<% end %>
	</table>
</div>
</div>



</div>
</div>

app/views/books/show.html.erb
<div class="container">
	<div class="row">

<% if flash[:notice] %>
      <div class="flash">
        <%= flash[:notice] %>
      </div>
    <% end %>

<% if @book.errors.any? %>
      <h2><%= @book.errors.count %>件のerror</h2>
      <ul>
      <% @book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
  <% end %>

<div class="col-xs-3">
<div class="user-info-box">
	<h2>User info</h2>
	<div class="image">
		 <%= attachment_image_tag @user, :profile_image, :fill, 100, 100, format: 'jpeg', class: "img-rounded pull-left profile-img", fallback: "no_image.jpg" %> 
	</div>
	<table class="table">
		<tr>
		<th>name</th>
		<th><%= @user.name %></th>
		</tr>
		<tr>
		<th>introduction</th>
		<th><%= @user.introduction %></th>
	 	</tr>
	</table>
	<div class="user-info-configuration">
		<% if @user.id == current_user.id %>
		<%= link_to edit_user_path(@user.id) do %>
			<span class="glyphicon glyphicon-wrench col-xs-12 btn btn-default editbutton" aria-hidden="true"></span>
		<% end %>
		<% end %>
		</div>
</div>

<div class="new-book-box">
	<h2>New book</h2>
	<%= form_for(@book) do |f| %>

	<div class="form-group">
	<label for="book-title">Title</label>
	<%= f.text_field :title, {class: "col-xs-12"} %>
	</div>
	<div class="form-group">
	<label class="book-opinion">Opinion</label>
	<%= f.text_area :body, {class: "col-xs-12"} %>
	</div>
	<div class="form-group">
	<%= f.submit 'Create Book', {class: "btn btn-primary col-xs-12 createbutton"} %>
	</div>
<% end %>
</div>
</div>

<div class="col-xs-9">
<div class="Books-index-box">
	<h2>Book detail</h2>
	<table class="table">
		<tr>
			<td><%= link_to user_path(@user.id) do %>
				<span> <%= attachment_image_tag @user, :profile_image, :fill, 100, 100, format: 'jpeg', class: "img-rounded pull-left profile-img", fallback: "no_image.jpg",size:'100x100' %> </span><br><br><br><br><br>
			<span><%= @user.name %></span>
			<% end %>
		    </td>
	<td><%= link_to book_path(@bookers.id) do %>
		<span><%= @bookers.title %></span>
		<% end %>
	</td>
	<td><%= @bookers.body %></td>
	<% if @bookers.user == current_user %>
	<td><%= link_to edit_book_path(@bookers.id) do %>
		<span class="btn-sm btn-success">Edit</span>
		<% end %>
	</td>
	<td><%= link_to book_path(@bookers.id), method: :delete, data: {confirm: "削除しますか？"} do %>
		<span class="btn-sm btn-danger">Destroy</span>
		<% end %>
	</td>
	<% end %>
		</tr>
    </table>
</div>
</div>

</div>
</div>

app/views/homes/about.html.erb
<div class="container">

<h1>Welcome to <span class="glyphicon glyphicon-book" aria-hidden="true"></span>Bookers!</h1>

</div>

app/views/homes/top.html.erb
<div class="container">
	<div class="row">

<% if flash[:notice] %>
      <div class="flash">
        <%= flash[:notice] %>
      </div>
    <% end %>

		<div class="top-message col-md-6 col-md-offset-3">
			<h1>welcome to <span class="glyphicon glyphicon-book" aria-hidden="true"></span>Bookers !!</h1>
			<p>in <span class="glyphicon glyphicon-book" aria-hidden="true"></span><strong>Bookers</strong>,<br>
				you can share and exchange your opinions , inpressions , and
				emotions<br> about various books!</p>
			<div class="btn-wrapper">
				<%= link_to 'Log in', new_user_session_path, class: "btn btn-info col-xs-10 col-xs-offset-1 " %>
				<%= link_to 'Sign up', new_user_registration_path, class: "btn btn-success col-xs-10 col-xs-offset-1" %>
			</div>
		</div>
	</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NewBookers</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
     <header class="navbar navbar-fixed-top navbar-inverse">
      <div class="container">
      <nav class="nav navbar-nav navbar-left">
        <p class="header-headline">Bookers</p>
      </nav>
      <nav>
        <ul class="nav navbar-nav navbar-right">
          <% if user_signed_in? %>
          <li><%= link_to user_path(current_user.id) do %>
            <span class="glyphicon glyphicon-home small" aria-hidden="true"> Home</span>
          <% end %>
          </li>
          <li>
          <%= link_to ("/users") do %>
            <span class="glyphicon glyphicon-user small" aria-hidden="true"> Users</span>
          <% end %>
          </li>
          <li>
          <%= link_to ("/books") do %>
            <span class="glyphicon glyphicon-book small" aria-hidden="true"> Books</span>
          <% end %>
          </li>
          <li>
          <%= link_to destroy_user_session_path, method: :delete do %>
            <span class="glyphicon glyphicon-new-window small" aria-hidden="true"> logout</span>
          <% end %>
           </li>
          <% else %>
          <li>
          <%= link_to ("/") do %>
            <span class="glyphicon glyphicon-home small" aria-hidden="true"> Home</span>
          <% end %>
          </li>
          <li>
          <%= link_to ("/home/about") do %>
            <span class="glyphicon glyphicon-link small" aria-hidden="true"> About</span>
          <% end %>
          </li>
          <li>
          <%= link_to ("/users/sign_up") do %>
            <span class="glyphicon glyphicon-new-window small" aria-hidden="true"> sign up</span>
          <% end %>
          </li>
          <li>
          <%= link_to ("/users/sign_in") do %>
            <span class="glyphicon glyphicon-log-out small" aria-hidden="true"> login</span>
          <% end %>
          </li>
          <% end %>

        </ul>
      </nav>
    </div>
     </header>
    <%= yield %>

    <footer>
      <div class="container">
        <div class="row">
          <div class="col-xs-10 col-xs-offset-9">
            <span>CopyRight Infratop.inc</span>
          </div>
        </div>
      </div>


  </body>
</html>

app/views/users/edit.html.erb
<div class="container">
	<div class="row">

<h2>User info</h2>

<%= form_for(@user) do |f| %>

<% if @user.errors.any? %>
      <h2><%= @user.errors.count %>件のerror</h2>
      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
  <% end %>
  	<div class="form-group">
	<label>Name</label>
	<%= f.text_field :name %>
	</div>
	<div class="form-group">
	<label>Image</label>
	<%= f.attachment_field :profile_image %>
	</div>
	<div class="form-group">
	<label>Introduction</label>
	<%= f.text_area :introduction %>
	</div>
	<%= f.submit "Update User" %>
<% end %>


</div>
</div>

app/views/users/index.html.erb
<div class="container">
	<div class="row">

<% if flash[:notice] %>
      <div class="flash">
        <%= flash[:notice] %>
      </div>
    <% end %>

<% if @book.errors.any? %>
      <h2><%= @book.errors.count %>件のerror</h2>
      <ul>
      <% @book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
  <% end %>

<div class="col-xs-3">
<div class="user-info-box">
	<h2>User info</h2>
	<div class="image">
		 <%= attachment_image_tag @user, :profile_image, :fill, 100, 100, format: 'jpeg', class: "img-rounded pull-left profile-img", fallback: "no_image.jpg" %> 
	</div>
	<table class="table">
		<tr>
		<th>name</th>
		<th><%= @user.name %></th>
		</tr>
		<tr>
		<th>introduction</th>
		<th><%= @user.introduction %></th>
	 	</tr>
	</table>
	<div class="user-info-configuration">
		<% if @user.id == current_user.id %>
		<%= link_to edit_user_path(@user.id) do %>
			<span class="glyphicon glyphicon-wrench col-xs-12 btn btn-default editbutton" aria-hidden="true"></span>
		<% end %>
		<% end %>
		</div>
</div>

<div class="new-book-box">
	<h2>New book</h2>
	<%= form_for(@book) do |f| %>

	<div class="form-group">
	<label for="book-title">Title</label>
	<%= f.text_field :title, {class: "col-xs-12"} %>
	</div>
	<div class="form-group">
	<label class="book-opinion">Opinion</label>
	<%= f.text_area :body, {class: "col-xs-12"} %>
	</div>
	<div class="form-group">
	<%= f.submit 'Create Book', {class: "btn btn-primary col-xs-12 createbutton"} %>
	</div>
	<% end %>
</div>
</div>

<div class="col-xs-9">
<div class="users-index-box">
	<h2>Users</h2>

	<table class ="table">
		<thead>
			<tr>
				<th>image</th> <th>name</th> <th></th>
			</tr>
		</thead>

		<tbody>
	    <% @users.each do |user| %>
		<tr>
			<td><%= attachment_image_tag user, :profile_image, :fill, 40, 40, format: 'jpeg', class: "img-rounded pull-left profile-img", fallback: "no_image.jpg",size:'40x40' %></td>
			<td><%= user.name %></td>
			<td><%= link_to 'Show', user_path(user.id) %></td>
		</tr>
		</tbody>
		<% end %>
	</table>
</div>
</div>

</div>
</div>

app/views/users/show.html.erb
<div class="container">
	<div class="row">

<% if flash[:notice] %>
      <div class="flash">
        <%= flash[:notice] %>
      </div>
    <% end %>
    
<% if @book.errors.any? %>
      <h2><%= @book.errors.count %>件のerror</h2>
      <ul>
      <% @book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
  <% end %>


<div class="col-xs-3">
<div class="user-info-box">
	<h2>User info</h2>
	<div class="image">
		 <%= attachment_image_tag @user, :profile_image, :fill, 100, 100, format: 'jpeg', class: "img-rounded pull-left profile-img", fallback: "no_image.jpg" %> 
	</div>
	<table class="table">
		<tr>
		<th>name</th>
		<th><%= @user.name %></th>
		</tr>
		<tr>
		<th>introduction</th>
		<th><%= @user.introduction %></th>
	 	</tr>
	</table>
	<div class="user-info-configuration">
		<% if @user.id == current_user.id %>
		<%= link_to edit_user_path(@user.id) do %>
			<span class="glyphicon glyphicon-wrench col-xs-12 btn btn-default editbutton" aria-hidden="true"></span>
		<% end %>
		<% end %>
		</div>
</div>

<div class="new-book-box">
	<h2>New book</h2>
	<%= form_for(@book) do |f| %>

	<div class="form-group">
	<label for="book-title">Title</label>
	<%= f.text_field :title, {class: "col-xs-12"} %>
	</div>
	<div class="form-group">
	<label class="book-opinion">Opinion</label>
	<%= f.text_area :body, {class: "col-xs-12"} %>
	</div>
	<div class="form-group">
	<%= f.submit 'Create Book', {class: "btn btn-primary col-xs-12 createbutton"} %>
	</div>
<% end %>
</div>

</div>

<div class="col-xs-9">
<div class="Books-index-box">
	<h2>Books</h2>
	<table class="table">
		<thead>
		<tr>
			<th></th><th>Title</th> <th>opinion</th> 
		</tr>
	    </thead>

	    <tbody>
	    <% @books.each do |book| %>
		<tr>
			<td><%= attachment_image_tag @user, :profile_image, :fill, 40, 40, format: 'jpeg', class: "img-rounded pull-left profile-img", fallback: "no_image.jpg",size:'40x40' %></td>
			<td><%= link_to book.title, book_path(book.id) %></td>
			<td><%= book.body %></td>
		</tr>
		</tbody>
		<% end %>
	</table>
</div>
</div>

</div>
</div>